const express = require('express');
const router = express.Router();

const PROCEDURES = [
  // ── IV & INJECTIONS ──────────────────────────────────────────────
  { code: 'PROC-001', name: 'IV Cannulation' },
  { code: 'PROC-002', name: 'IV Fluid Administration' },
  { code: 'PROC-003', name: 'IV Drug Administration' },
  { code: 'PROC-004', name: 'IV Antibiotic Administration' },
  { code: 'PROC-005', name: 'IM Injection' },
  { code: 'PROC-006', name: 'IV Injection' },
  { code: 'PROC-007', name: 'Subcutaneous Injection' },
  { code: 'PROC-008', name: 'Intradermal Injection' },
  { code: 'PROC-009', name: 'Central Venous Catheter Insertion' },
  { code: 'PROC-010', name: 'Central Venous Catheter Removal' },
  { code: 'PROC-011', name: 'PICC Line Insertion' },
  { code: 'PROC-012', name: 'PICC Line Removal' },
  { code: 'PROC-013', name: 'Arterial Line Insertion' },
  { code: 'PROC-014', name: 'Arterial Line Removal' },
  { code: 'PROC-015', name: 'Blood Transfusion' },
  { code: 'PROC-016', name: 'Platelet Transfusion' },
  { code: 'PROC-017', name: 'Fresh Frozen Plasma Transfusion' },

  // ── WOUNDS & SKIN ────────────────────────────────────────────────
  { code: 'PROC-018', name: 'Wound Dressing - Simple' },
  { code: 'PROC-019', name: 'Wound Dressing - Complex' },
  { code: 'PROC-020', name: 'Wound Suturing - Simple' },
  { code: 'PROC-021', name: 'Wound Suturing - Deep/Layered' },
  { code: 'PROC-022', name: 'Wound Debridement' },
  { code: 'PROC-023', name: 'Wound Irrigation' },
  { code: 'PROC-024', name: 'Suture Removal' },
  { code: 'PROC-025', name: 'Abscess Incision & Drainage' },
  { code: 'PROC-026', name: 'Cyst Excision' },
  { code: 'PROC-027', name: 'Lipoma Excision' },
  { code: 'PROC-028', name: 'Sebaceous Cyst Removal' },
  { code: 'PROC-029', name: 'Burn Dressing - Minor' },
  { code: 'PROC-030', name: 'Burn Dressing - Major' },
  { code: 'PROC-031', name: 'Skin Grafting - Split Thickness' },
  { code: 'PROC-032', name: 'Skin Grafting - Full Thickness' },
  { code: 'PROC-033', name: 'Skin Biopsy' },
  { code: 'PROC-034', name: 'Punch Biopsy' },
  { code: 'PROC-035', name: 'Wart Removal' },
  { code: 'PROC-036', name: 'Mole Removal' },
  { code: 'PROC-037', name: 'Nail Removal - Partial' },
  { code: 'PROC-038', name: 'Nail Removal - Total' },
  { code: 'PROC-039', name: 'Ingrown Toenail Procedure' },
  { code: 'PROC-040', name: 'Keloid Excision' },
  { code: 'PROC-041', name: 'Skin Tag Removal' },
  { code: 'PROC-042', name: 'Foreign Body Removal - Skin' },
  { code: 'PROC-043', name: 'Debridement of Ulcer' },

  // ── AIRWAY & RESPIRATORY ─────────────────────────────────────────
  { code: 'PROC-044', name: 'Oxygen Therapy' },
  { code: 'PROC-045', name: 'Nebulization' },
  { code: 'PROC-046', name: 'Intubation - Endotracheal' },
  { code: 'PROC-047', name: 'Extubation' },
  { code: 'PROC-048', name: 'Tracheostomy - Emergency' },
  { code: 'PROC-049', name: 'Tracheostomy - Elective' },
  { code: 'PROC-050', name: 'Tracheostomy Care & Suctioning' },
  { code: 'PROC-051', name: 'Chest Tube Insertion' },
  { code: 'PROC-052', name: 'Chest Tube Removal' },
  { code: 'PROC-053', name: 'Pleural Tap / Thoracocentesis' },
  { code: 'PROC-054', name: 'Bronchoscopy' },
  { code: 'PROC-055', name: 'Mechanical Ventilation' },
  { code: 'PROC-056', name: 'CPAP Application' },
  { code: 'PROC-057', name: 'BiPAP Application' },
  { code: 'PROC-058', name: 'Intercostal Drain Insertion' },

  // ── CARDIAC ──────────────────────────────────────────────────────
  { code: 'PROC-059', name: 'CPR / Resuscitation' },
  { code: 'PROC-060', name: 'Defibrillation' },
  { code: 'PROC-061', name: 'Cardioversion' },
  { code: 'PROC-062', name: 'ECG Recording' },
  { code: 'PROC-063', name: 'Echocardiogram' },
  { code: 'PROC-064', name: 'Pericardiocentesis' },
  { code: 'PROC-065', name: 'Temporary Pacemaker Insertion' },

  // ── GASTROINTESTINAL ─────────────────────────────────────────────
  { code: 'PROC-066', name: 'Nasogastric Tube Insertion' },
  { code: 'PROC-067', name: 'Nasogastric Tube Removal' },
  { code: 'PROC-068', name: 'Nasogastric Tube Feeding' },
  { code: 'PROC-069', name: 'Ascitic Tap / Paracentesis' },
  { code: 'PROC-070', name: 'Endoscopy - Upper GI' },
  { code: 'PROC-071', name: 'Endoscopy - Lower GI / Colonoscopy' },
  { code: 'PROC-072', name: 'Appendectomy' },
  { code: 'PROC-073', name: 'Hernia Repair - Inguinal' },
  { code: 'PROC-074', name: 'Hernia Repair - Umbilical' },
  { code: 'PROC-075', name: 'Hernia Repair - Femoral' },
  { code: 'PROC-076', name: 'Hemorrhoidectomy' },
  { code: 'PROC-077', name: 'Hemorrhoid Banding' },
  { code: 'PROC-078', name: 'Anal Fissure Repair' },
  { code: 'PROC-079', name: 'Colostomy Formation' },
  { code: 'PROC-080', name: 'Colostomy Reversal' },
  { code: 'PROC-081', name: 'Rectal Examination' },
  { code: 'PROC-082', name: 'Proctoscopy' },
  { code: 'PROC-083', name: 'Sigmoidoscopy' },
  { code: 'PROC-084', name: 'Feeding Gastrostomy' },
  { code: 'PROC-085', name: 'Liver Biopsy' },
  { code: 'PROC-086', name: 'Cholecystectomy' },
  { code: 'PROC-087', name: 'Splenectomy' },

  // ── UROLOGICAL ───────────────────────────────────────────────────
  { code: 'PROC-088', name: 'Urinary Catheterization - Male' },
  { code: 'PROC-089', name: 'Urinary Catheterization - Female' },
  { code: 'PROC-090', name: 'Urinary Catheter Removal' },
  { code: 'PROC-091', name: 'Suprapubic Catheter Insertion' },
  { code: 'PROC-092', name: 'Suprapubic Catheter Removal' },
  { code: 'PROC-093', name: 'Cystoscopy' },
  { code: 'PROC-094', name: 'Circumcision - Adult' },
  { code: 'PROC-095', name: 'Circumcision - Paediatric' },
  { code: 'PROC-096', name: 'Hydrocelectomy' },
  { code: 'PROC-097', name: 'Vasectomy' },
  { code: 'PROC-098', name: 'Vasectomy Reversal' },
  { code: 'PROC-099', name: 'Orchidectomy' },
  { code: 'PROC-100', name: 'Orchidopexy' },
  { code: 'PROC-101', name: 'Prostate Biopsy' },
  { code: 'PROC-102', name: 'Kidney Biopsy' },
  { code: 'PROC-103', name: 'Dialysis - Haemodialysis' },
  { code: 'PROC-104', name: 'Dialysis - Peritoneal' },
  { code: 'PROC-105', name: 'Nephrostomy Insertion' },
  { code: 'PROC-106', name: 'Ureteric Stent Insertion' },
  { code: 'PROC-107', name: 'Ureteric Stent Removal' },
  { code: 'PROC-108', name: 'Lithotripsy' },

  // ── GYNAECOLOGY & OBSTETRICS ─────────────────────────────────────
  { code: 'PROC-109', name: 'Normal Vaginal Delivery' },
  { code: 'PROC-110', name: 'Assisted Vaginal Delivery - Forceps' },
  { code: 'PROC-111', name: 'Assisted Vaginal Delivery - Vacuum' },
  { code: 'PROC-112', name: 'Caesarean Section - Elective' },
  { code: 'PROC-113', name: 'Caesarean Section - Emergency' },
  { code: 'PROC-114', name: 'Episiotomy' },
  { code: 'PROC-115', name: 'Episiotomy Repair' },
  { code: 'PROC-116', name: 'Perineal Tear Repair - 1st Degree' },
  { code: 'PROC-117', name: 'Perineal Tear Repair - 2nd Degree' },
  { code: 'PROC-118', name: 'Perineal Tear Repair - 3rd/4th Degree' },
  { code: 'PROC-119', name: 'Manual Removal of Placenta' },
  { code: 'PROC-120', name: 'Manual Vacuum Aspiration (MVA)' },
  { code: 'PROC-121', name: 'Dilatation & Curettage (D&C)' },
  { code: 'PROC-122', name: 'Evacuation of Retained Products' },
  { code: 'PROC-123', name: 'IUCD Insertion' },
  { code: 'PROC-124', name: 'IUCD Removal' },
  { code: 'PROC-125', name: 'Implant Insertion - Jadelle/Implanon' },
  { code: 'PROC-126', name: 'Implant Removal' },
  { code: 'PROC-127', name: 'Tubal Ligation - Laparoscopic' },
  { code: 'PROC-128', name: 'Tubal Ligation - Mini Laparotomy' },
  { code: 'PROC-129', name: 'Hysterectomy - Total Abdominal' },
  { code: 'PROC-130', name: 'Hysterectomy - Vaginal' },
  { code: 'PROC-131', name: 'Hysterectomy - Laparoscopic' },
  { code: 'PROC-132', name: 'Myomectomy' },
  { code: 'PROC-133', name: 'Ovarian Cystectomy' },
  { code: 'PROC-134', name: 'Oophorectomy' },
  { code: 'PROC-135', name: 'Pap Smear' },
  { code: 'PROC-136', name: 'Colposcopy' },
  { code: 'PROC-137', name: 'Cervical Biopsy' },
  { code: 'PROC-138', name: 'LEEP/LLETZ Procedure' },
  { code: 'PROC-139', name: 'Cervical Cerclage' },
  { code: 'PROC-140', name: 'Cervical Cerclage Removal' },
  { code: 'PROC-141', name: 'Hysteroscopy' },
  { code: 'PROC-142', name: 'Laparoscopy - Diagnostic' },
  { code: 'PROC-143', name: 'Laparoscopy - Operative' },
  { code: 'PROC-144', name: 'Ectopic Pregnancy Surgery' },
  { code: 'PROC-145', name: 'Vulvar Biopsy' },
  { code: 'PROC-146', name: 'Bartholin Cyst Drainage' },
  { code: 'PROC-147', name: 'Bartholin Cyst Marsupialisation' },

  // ── ORTHOPAEDIC ──────────────────────────────────────────────────
  { code: 'PROC-148', name: 'Splinting / Immobilization' },
  { code: 'PROC-149', name: 'Plaster of Paris Application' },
  { code: 'PROC-150', name: 'Plaster of Paris Removal' },
  { code: 'PROC-151', name: 'Fracture Reduction - Closed' },
  { code: 'PROC-152', name: 'Fracture Reduction - Open' },
  { code: 'PROC-153', name: 'Internal Fixation - ORIF' },
  { code: 'PROC-154', name: 'External Fixation' },
  { code: 'PROC-155', name: 'Intramedullary Nail Insertion' },
  { code: 'PROC-156', name: 'Joint Aspiration - Knee' },
  { code: 'PROC-157', name: 'Joint Aspiration - Hip' },
  { code: 'PROC-158', name: 'Joint Aspiration - Shoulder' },
  { code: 'PROC-159', name: 'Joint Injection - Steroid' },
  { code: 'PROC-160', name: 'Hip Replacement - Total' },
  { code: 'PROC-161', name: 'Knee Replacement - Total' },
  { code: 'PROC-162', name: 'Arthroscopy - Knee' },
  { code: 'PROC-163', name: 'Arthroscopy - Shoulder' },
  { code: 'PROC-164', name: 'Amputation - Below Knee' },
  { code: 'PROC-165', name: 'Amputation - Above Knee' },
  { code: 'PROC-166', name: 'Amputation - Below Elbow' },
  { code: 'PROC-167', name: 'Amputation - Above Elbow' },
  { code: 'PROC-168', name: 'Finger/Toe Amputation' },
  { code: 'PROC-169', name: 'Tendon Repair' },
  { code: 'PROC-170', name: 'Nerve Repair' },
  { code: 'PROC-171', name: 'Bone Biopsy' },
  { code: 'PROC-172', name: 'Bone Grafting' },

  // ── NEUROLOGY & NEUROSURGERY ─────────────────────────────────────
  { code: 'PROC-173', name: 'Lumbar Puncture' },
  { code: 'PROC-174', name: 'Burr Hole Drainage' },
  { code: 'PROC-175', name: 'Craniotomy' },
  { code: 'PROC-176', name: 'Ventriculoperitoneal Shunt Insertion' },
  { code: 'PROC-177', name: 'Ventriculoperitoneal Shunt Revision' },
  { code: 'PROC-178', name: 'Nerve Block' },
  { code: 'PROC-179', name: 'Spinal Anaesthesia' },
  { code: 'PROC-180', name: 'Epidural Anaesthesia' },
  { code: 'PROC-181', name: 'EEG Recording' },

  // ── ENT ──────────────────────────────────────────────────────────
  { code: 'PROC-182', name: 'Ear Syringing' },
  { code: 'PROC-183', name: 'Foreign Body Removal - Ear' },
  { code: 'PROC-184', name: 'Foreign Body Removal - Nose' },
  { code: 'PROC-185', name: 'Foreign Body Removal - Throat' },
  { code: 'PROC-186', name: 'Nasal Packing - Anterior' },
  { code: 'PROC-187', name: 'Nasal Packing - Posterior' },
  { code: 'PROC-188', name: 'Tonsillectomy' },
  { code: 'PROC-189', name: 'Adenoidectomy' },
  { code: 'PROC-190', name: 'Myringotomy & Grommet Insertion' },
  { code: 'PROC-191', name: 'Septoplasty' },
  { code: 'PROC-192', name: 'Functional Endoscopic Sinus Surgery' },
  { code: 'PROC-193', name: 'Mastoidectomy' },
  { code: 'PROC-194', name: 'Laryngoscopy - Direct' },
  { code: 'PROC-195', name: 'Tracheostomy - ENT' },

  // ── OPHTHALMOLOGY ────────────────────────────────────────────────
  { code: 'PROC-196', name: 'Eye Irrigation' },
  { code: 'PROC-197', name: 'Foreign Body Removal - Eye' },
  { code: 'PROC-198', name: 'Eye Pad Application' },
  { code: 'PROC-199', name: 'Cataract Extraction' },
  { code: 'PROC-200', name: 'Intraocular Lens Insertion' },
  { code: 'PROC-201', name: 'Glaucoma Surgery' },
  { code: 'PROC-202', name: 'Chalazion Removal' },
  { code: 'PROC-203', name: 'Pterygium Excision' },
  { code: 'PROC-204', name: 'Retinal Laser Treatment' },
  { code: 'PROC-205', name: 'Intravitreal Injection' },

  // ── DENTAL ───────────────────────────────────────────────────────
  { code: 'PROC-206', name: 'Tooth Extraction - Simple' },
  { code: 'PROC-207', name: 'Tooth Extraction - Surgical' },
  { code: 'PROC-208', name: 'Wisdom Tooth Extraction' },
  { code: 'PROC-209', name: 'Dental Filling' },
  { code: 'PROC-210', name: 'Root Canal Treatment' },
  { code: 'PROC-211', name: 'Dental Scaling & Polishing' },
  { code: 'PROC-212', name: 'Dental Crown Placement' },
  { code: 'PROC-213', name: 'Dental Bridge' },
  { code: 'PROC-214', name: 'Denture Fitting' },
  { code: 'PROC-215', name: 'Dental Abscess Drainage' },
  { code: 'PROC-216', name: 'Orthodontic Braces' },
  { code: 'PROC-217', name: 'Jaw Fracture Wiring' },

  // ── ONCOLOGY ─────────────────────────────────────────────────────
  { code: 'PROC-218', name: 'Chemotherapy Administration' },
  { code: 'PROC-219', name: 'Fine Needle Aspiration (FNAC)' },
  { code: 'PROC-220', name: 'Core Biopsy' },
  { code: 'PROC-221', name: 'Bone Marrow Biopsy' },
  { code: 'PROC-222', name: 'Port-a-Cath Insertion' },
  { code: 'PROC-223', name: 'Port-a-Cath Removal' },
  { code: 'PROC-224', name: 'Mastectomy - Simple' },
  { code: 'PROC-225', name: 'Mastectomy - Modified Radical' },
  { code: 'PROC-226', name: 'Lumpectomy' },
  { code: 'PROC-227', name: 'Lymph Node Dissection' },
  { code: 'PROC-228', name: 'Tumour Excision' },

  // ── PAEDIATRIC ───────────────────────────────────────────────────
  { code: 'PROC-229', name: 'Neonatal Resuscitation' },
  { code: 'PROC-230', name: 'Umbilical Catheter Insertion' },
  { code: 'PROC-231', name: 'Neonatal Intubation' },
  { code: 'PROC-232', name: 'Paediatric IV Cannulation' },
  { code: 'PROC-233', name: 'Intraosseous Access' },
  { code: 'PROC-234', name: 'Circumcision - Neonatal' },
  { code: 'PROC-235', name: 'Pyloromyotomy' },
  { code: 'PROC-236', name: 'Paediatric Hernia Repair' },

  // ── EMERGENCY & ICU ──────────────────────────────────────────────
  { code: 'PROC-237', name: 'Emergency Thoracotomy' },
  { code: 'PROC-238', name: 'Emergency Laparotomy' },
  { code: 'PROC-239', name: 'Trauma Primary Survey' },
  { code: 'PROC-240', name: 'Trauma Secondary Survey' },
  { code: 'PROC-241', name: 'FAST Ultrasound' },
  { code: 'PROC-242', name: 'DPL - Diagnostic Peritoneal Lavage' },
  { code: 'PROC-243', name: 'Cricothyrotomy - Emergency' },
  { code: 'PROC-244', name: 'Tension Pneumothorax Needle Decompression' },
  { code: 'PROC-245', name: 'Intraosseous Infusion' },

  // ── GENERAL ──────────────────────────────────────────────────────
  { code: 'PROC-246', name: 'Blood Glucose Monitoring' },
  { code: 'PROC-247', name: 'Blood Pressure Monitoring' },
  { code: 'PROC-248', name: 'Pulse Oximetry' },
  { code: 'PROC-249', name: 'Temperature Monitoring' },
  { code: 'PROC-250', name: 'Urinalysis' },
  { code: 'PROC-251', name: 'Stool Examination' },
  { code: 'PROC-252', name: 'Gastric Lavage' },
  { code: 'PROC-253', name: 'Enema Administration' },
  { code: 'PROC-254', name: 'Physiotherapy Session' },
  { code: 'PROC-255', name: 'Occupational Therapy Session' },
  { code: 'PROC-256', name: 'Speech Therapy Session' },
  { code: 'PROC-257', name: 'Phototherapy - Neonatal Jaundice' },
  { code: 'PROC-258', name: 'Exchange Transfusion' },
  { code: 'PROC-259', name: 'Insulin Administration - IV Infusion' },
  { code: 'PROC-260', name: 'Thrombolysis Administration' },
];

router.get('/search', (req, res) => {
  const term = req.query.term?.toLowerCase();
  if (!term) return res.status(400).json({ message: 'Search term required' });
  const results = PROCEDURES.filter(p =>
    p.name.toLowerCase().includes(term) || p.code.toLowerCase().includes(term)
  );
  res.json(results);
});

module.exports = router;
