ALTER TABLE lab_requests
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS result_value VARCHAR(100),
  ADD COLUMN IF NOT EXISTS result_unit VARCHAR(50),
  ADD COLUMN IF NOT EXISTS reference_range VARCHAR(100),
  ADD COLUMN IF NOT EXISTS result_flag VARCHAR(20) DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS technician_notes TEXT;
